import { ArrowRight, BookOpenCheck, Check, ClipboardList, GraduationCap, Map, MapPin, School, UserRound, Users, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { DashboardPreview, FinancePreview, MapPreview, StudentsPreview } from "./product-previews";

export function PresentationNavbar(){return <header className="sticky top-0 z-50 border-b border-neutral-200/80 bg-white/90 backdrop-blur"><nav className="mx-auto flex h-16 max-w-7xl items-center px-5 sm:px-7" aria-label="Navegação principal"><Link to="/apresentacao" className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-neutral-900 text-sm text-white">V</span>VanEscolar</Link><div className="ml-auto hidden items-center gap-6 text-sm text-neutral-600 md:flex"><a href="#recursos">Recursos</a><a href="#mapa">Mapa</a><a href="#como-funciona">Como funciona</a></div><Button asChild variant="outline" className="ml-5"><Link to="/login">Entrar</Link></Button></nav></header>}

export function HeroSection(){return <section className="relative overflow-hidden border-b"><div className="presentation-grid absolute inset-0 opacity-50"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-7 lg:grid-cols-[.9fr_1.1fr] lg:py-28"><div><Badge className="mb-5">Gestão para transporte escolar</Badge><h1 className="max-w-xl text-4xl font-semibold leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Sua operação escolar inteira, em um só lugar.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-neutral-600">Organize alunos, responsáveis, escolas, motoristas, veículos e financeiro sem depender de informações espalhadas.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-11 px-5"><a href="#recursos">Conhecer os recursos <ArrowRight size={16}/></a></Button><Button asChild variant="outline" className="h-11 px-5"><Link to="/login">Entrar no sistema</Link></Button></div><p className="mt-5 flex items-center gap-2 text-sm text-neutral-500"><Check size={15} className="text-emerald-600"/>Informação clara para a rotina de quem administra</p></div><div className="presentation-float"><DashboardPreview/></div></div></section>}

export function ProblemSection(){const pains=["Alunos em planilhas diferentes","Endereços perdidos em conversas","Cobranças sem uma visão clara","Dados da frota espalhados"];return <section className="bg-neutral-950 py-20 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-7"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-medium text-amber-300">Quando tudo fica separado</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">A rotina exige respostas rápidas. A informação também.</h2><p className="mt-4 leading-7 text-neutral-400">Encontrar um contato, conferir um endereço ou entender uma pendência não deveria exigir várias planilhas e anotações.</p></div><div className="grid gap-3 sm:grid-cols-2">{pains.map(x=><div className="rounded-lg border border-white/15 bg-white/5 p-5 text-sm text-neutral-200" key={x}><span className="mr-3 text-amber-300">—</span>{x}</div>)}</div></div><div className="mt-12 border-t border-white/15 pt-8 text-xl font-medium">O VanEscolar reúne a operação e conecta as informações que você usa todos os dias.</div></div></section>}

export function ProductSections(){return <><section id="recursos" className="scroll-mt-20 py-24"><div className="mx-auto max-w-7xl px-5 sm:px-7"><SectionIntro eyebrow="O produto real, de ponta a ponta" title="Controle que começa no aluno e chega até o financeiro" text="Veja a operação em uma interface direta: os cadastros essenciais, a visão geográfica e os valores do negócio trabalham no mesmo sistema."/><div className="mt-14 grid items-center gap-12 lg:grid-cols-2"><div><Badge>Alunos e responsáveis</Badge><h3 className="mt-4 text-3xl font-semibold tracking-tight">Toda a vida do aluno organizada</h3><p className="mt-4 leading-7 text-neutral-600">Nome, status, endereço, escola e responsáveis ficam relacionados. Assim, você localiza as informações necessárias sem procurar em vários lugares.</p><ul className="mt-6 space-y-3 text-sm"><Benefit text="Responsáveis vinculados a cada aluno"/><Benefit text="Escola e endereço prontos para consulta"/><Benefit text="Busca e status para uma gestão mais clara"/></ul></div><StudentsPreview/></div></div></section><section id="mapa" className="scroll-mt-20 border-y bg-neutral-50 py-24"><div className="mx-auto max-w-7xl px-5 sm:px-7"><div className="grid items-end gap-6 lg:grid-cols-2"><div><p className="text-sm font-medium text-blue-700">Mapa de alunos</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Entenda sua operação no espaço</h2></div><p className="leading-7 text-neutral-600">Visualize onde os alunos estão, identifique suas escolas pelas cores e veja o ponto inicial da van. Use os filtros para observar cada parte da operação — sem promessas de rotas automáticas.</p></div><div className="mt-12"><MapPreview/></div></div></section><section className="py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-7 lg:grid-cols-2"><FinancePreview/><div><Badge>Gestão financeira</Badge><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Saiba o que entrou, o que saiu e o que está pendente</h2><p className="mt-4 leading-7 text-neutral-600">Receitas, despesas, mensalidades e pagamentos aparecem em uma visão financeira organizada, com valores a receber, em atraso e a pagar.</p><ul className="mt-6 space-y-3 text-sm"><Benefit text="Acompanhe saldo, entradas e saídas"/><Benefit text="Identifique lançamentos pendentes ou em atraso"/><Benefit text="Relacione valores a alunos, responsáveis e veículos"/></ul></div></div></section></>}

export function OperationSection(){const flow=[{i:GraduationCap,t:"Aluno"},{i:Users,t:"Responsável"},{i:School,t:"Escola"},{i:UserRound,t:"Motorista"},{i:Map,t:"Mapa"},{i:WalletCards,t:"Financeiro"}];return <section className="border-y bg-neutral-950 py-24 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-7"><SectionIntro eyebrow="Informações conectadas" title="Uma operação, não uma coleção de cadastros" text="Cada parte ajuda a formar uma visão mais completa do transporte escolar." dark/><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{flow.map(({i:Icon,t},index)=><div className="relative rounded-lg border border-white/15 bg-white/5 p-5" key={t}><Icon className="text-amber-300" size={20}/><strong className="mt-5 block">{t}</strong>{index<flow.length-1&&<ArrowRight className="absolute -right-5 top-1/2 z-10 hidden text-neutral-600 lg:block" size={24}/>}</div>)}</div></div></section>}

export function BenefitsAndSteps(){const benefits=[{i:ClipboardList,t:"Tudo centralizado",d:"Menos dependência de planilhas e anotações separadas."},{i:MapPin,t:"Visualização geográfica",d:"Alunos, escolas e início da van organizados no mapa."},{i:WalletCards,t:"Financeiro organizado",d:"Clareza sobre receitas, despesas e pendências."},{i:BookOpenCheck,t:"Operação conectada",d:"Pessoas, escolas, frota e valores no mesmo sistema."}];return <><section className="py-24"><div className="mx-auto max-w-7xl px-5 sm:px-7"><SectionIntro eyebrow="Benefícios na rotina" title="Menos tempo procurando. Mais clareza para administrar."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(({i:Icon,t,d})=><Card className="p-6 transition-transform hover:-translate-y-1" key={t}><span className="grid size-10 place-items-center rounded-lg bg-neutral-100"><Icon size={19}/></span><h3 className="mt-5 font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{d}</p></Card>)}</div></div></section><section id="como-funciona" className="scroll-mt-20 border-y bg-neutral-50 py-24"><div className="mx-auto max-w-7xl px-5 sm:px-7"><SectionIntro eyebrow="Como funciona" title="Organize a base e acompanhe a operação"/><ol className="mt-12 grid gap-8 md:grid-cols-3">{[["01","Estruture sua operação","Organize motoristas, veículos, escolas e o ponto inicial da van."],["02","Conecte as pessoas","Relacione alunos aos seus responsáveis, escolas e endereços."],["03","Acompanhe o dia a dia","Consulte o mapa e mantenha receitas, despesas e mensalidades sob controle."]].map(([n,t,d])=><li className="border-t border-neutral-300 pt-5" key={n}><span className="text-sm font-semibold text-blue-700">{n}</span><h3 className="mt-4 text-xl font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{d}</p></li>)}</ol></div></section></>}

export function FinalCta(){return <><section className="px-5 py-24 sm:px-7"><div className="mx-auto max-w-5xl rounded-2xl bg-neutral-900 px-6 py-16 text-center text-white sm:px-12"><p className="text-sm font-medium text-amber-300">VanEscolar</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Sua operação pode ser mais simples de administrar.</h2><p className="mx-auto mt-4 max-w-xl text-neutral-400">Entre no sistema e concentre as informações do transporte escolar em um só lugar.</p><Button asChild className="mt-8 h-11 bg-white px-5 text-neutral-900 hover:bg-neutral-100"><Link to="/login">Entrar no VanEscolar <ArrowRight size={16}/></Link></Button></div></section><footer className="border-t"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-7 text-sm text-neutral-500 sm:flex-row sm:items-center sm:justify-between sm:px-7"><strong className="text-neutral-900">VanEscolar</strong><span>Gestão inteligente para transporte escolar.</span><Link className="hover:text-neutral-900" to="/login">Acessar o sistema</Link></div></footer></>}

function SectionIntro({eyebrow,title,text,dark=false}:{eyebrow:string;title:string;text?:string;dark?:boolean}){return <div className="max-w-3xl"><p className={`text-sm font-medium ${dark?"text-amber-300":"text-blue-700"}`}>{eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h2>{text&&<p className={`mt-4 max-w-2xl leading-7 ${dark?"text-neutral-400":"text-neutral-600"}`}>{text}</p>}</div>}
function Benefit({text}:{text:string}){return <li className="flex gap-3"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Check size={13}/></span>{text}</li>}
