import { BookOpenCheck, Bus, CarFront, GraduationCap, MapPin, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

const metrics = [["Alunos", "84"], ["Responsáveis", "71"], ["Motoristas", "6"], ["Veículos", "7"]] as const;
export function DashboardPreview() {
  return <ProductFrame title="Visão geral"><div className="grid grid-cols-2 border-y border-neutral-200 sm:grid-cols-4">{metrics.map(([label,value],i)=><div className={`p-3 sm:p-4 ${i%2 ? "border-l" : ""} ${i>1 ? "border-t sm:border-t-0" : ""}`} key={label}><p className="text-[11px] text-neutral-500">{label}</p><strong className="mt-1 block text-xl">{value}</strong></div>)}</div><div className="p-4"><div className="mb-3 flex items-center justify-between"><strong className="text-sm">Operação organizada</strong><Badge>Visão geral</Badge></div><div className="grid gap-2 sm:grid-cols-2"><MiniRow icon={Bus} title="Frota cadastrada" meta="Motoristas e veículos organizados"/><MiniRow icon={GraduationCap} title="Alunos organizados" meta="Responsáveis e escolas conectados"/></div></div></ProductFrame>;
}

export function StudentsPreview() {
  const rows = [["João Martins","Mariana Martins","Colégio Horizonte","Ativo"],["Ana Costa","Ricardo Costa","Escola Caminhos","Ativo"],["Lucas Rocha","Fernanda Rocha","Colégio Horizonte","Ativo"]];
  return <ProductFrame title="Alunos"><div className="overflow-hidden"><div className="grid grid-cols-[1.1fr_1.1fr_1fr_.5fr] gap-2 bg-neutral-50 px-4 py-2 text-[10px] font-medium uppercase tracking-wide text-neutral-500"><span>Aluno</span><span>Responsável</span><span>Escola</span><span>Status</span></div>{rows.map(row=><div className="grid grid-cols-[1.1fr_1.1fr_1fr_.5fr] gap-2 border-t px-4 py-3 text-xs" key={row[0]}><strong>{row[0]}</strong><span className="text-neutral-600">{row[1]}</span><span className="text-neutral-600">{row[2]}</span><span className="text-emerald-700">{row[3]}</span></div>)}</div><div className="grid gap-2 border-t bg-neutral-50 p-3 sm:grid-cols-3"><MiniRow icon={Users} title="Responsáveis" meta="Contatos relacionados"/><MiniRow icon={BookOpenCheck} title="Escolas" meta="Endereço e identificação"/><MiniRow icon={MapPin} title="Endereços" meta="Usados no mapa"/></div></ProductFrame>;
}

export function FinancePreview() {
  const entries = [["Mensalidade · João Martins","Recebido","+ R$ 620,00"],["Combustível · Van 01","Pago","− R$ 380,00"],["Mensalidade · Ana Costa","Pendente","+ R$ 590,00"]];
  return <ProductFrame title="Financeiro"><div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-4">{[["Saldo atual","R$ 14.280"],["Entradas","R$ 18.450"],["Saídas","R$ 4.170"],["A receber","R$ 3.280"]].map(([a,b])=><Card className="p-3" key={a}><p className="text-[10px] text-neutral-500">{a}</p><strong className="mt-1 block text-sm">{b}</strong></Card>)}</div><div className="border-t px-4"><p className="py-3 text-xs font-semibold">Lançamentos</p>{entries.map(([name,status,value])=><div className="flex items-center gap-3 border-t py-3 text-xs" key={name}><span className={`size-2 rounded-full ${status==="Pendente"?"bg-amber-500":"bg-emerald-500"}`}/><span className="min-w-0 flex-1 truncate font-medium">{name}</span><Badge variant="outline" className="hidden sm:inline-flex">{status}</Badge><strong>{value}</strong></div>)}</div></ProductFrame>;
}

export function MapPreview() {
  const markers=[{x:21,y:26,c:"#2563eb",t:"👤"},{x:47,y:18,c:"#2563eb",t:"👤"},{x:69,y:35,c:"#e11d48",t:"👤"},{x:35,y:68,c:"#e11d48",t:"👤"},{x:75,y:72,c:"#2563eb",t:"👤"},{x:54,y:50,c:"#facc15",t:"🚐"},{x:83,y:19,c:"#2563eb",t:"🏫"},{x:15,y:77,c:"#e11d48",t:"🏫"}];
  return <div className="overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-xl shadow-neutral-950/10"><div className="flex items-center gap-2 border-b px-4 py-3"><span className="size-2.5 rounded-full bg-red-400"/><span className="size-2.5 rounded-full bg-amber-400"/><span className="size-2.5 rounded-full bg-emerald-400"/><strong className="ml-2 text-xs">Mapa de Alunos</strong></div><div className="grid min-h-[440px] md:grid-cols-[230px_1fr]"><aside className="border-b bg-white p-4 text-xs md:border-b-0 md:border-r"><label className="font-medium text-neutral-600">Van</label><div className="mt-1 rounded-md border p-2">Van 01 · ABC-1D23</div><label className="mt-4 block font-medium text-neutral-600">Escola</label><div className="mt-1 rounded-md border p-2">Todas as escolas</div><p className="mt-4 font-semibold">Filtros</p><div className="mt-2 flex gap-3 md:flex-col">{["Alunos","Escolas","Vans"].map(x=><span key={x}>☑ {x}</span>)}</div><div className="mt-4 grid grid-cols-3 gap-1 text-center">{[["84","alunos"],["2","escolas"],["1","van"]].map(x=><div className="rounded border p-2" key={x[1]}><b className="block">{x[0]}</b><small>{x[1]}</small></div>)}</div><p className="mt-4 font-semibold">Legenda</p><p className="mt-2">🚐 Ponto inicial da van</p><p>👤 Aluno</p><p>🏫 Escola</p></aside><div className="presentation-map relative min-h-[330px] overflow-hidden" aria-label="Mapa demonstrativo com alunos, escolas e ponto inicial da van">{markers.map((m,i)=><span className="absolute grid size-9 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-white text-base shadow-md" style={{left:`${m.x}%`,top:`${m.y}%`,background:m.c}} key={i}>{m.t}</span>)}</div></div></div>;
}

function ProductFrame({title,children}:{title:string;children:React.ReactNode}) { return <div className="overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-xl shadow-neutral-950/10"><div className="flex items-center border-b px-4 py-3"><div className="mr-3 flex gap-1.5"><span className="size-2.5 rounded-full bg-red-400"/><span className="size-2.5 rounded-full bg-amber-400"/><span className="size-2.5 rounded-full bg-emerald-400"/></div><strong className="text-xs">VanEscolar / {title}</strong></div>{children}</div> }
function MiniRow({icon:Icon,title,meta}:{icon:typeof CarFront;title:string;meta:string}) { return <div className="flex items-center gap-3 rounded-md border p-3"><span className="grid size-8 shrink-0 place-items-center rounded-md bg-neutral-100"><Icon size={15}/></span><span className="min-w-0"><strong className="block truncate text-xs">{title}</strong><small className="block truncate text-neutral-500">{meta}</small></span></div> }
